# Generated by Django 4.2.1 on 2023-05-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_BiblioTech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='dData_devolucao',
            new_name='Data_devolucao',
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='dData_emprestimo',
            new_name='Data_emprestimo',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='iAno_publicacao',
            new_name='Ano_publicacao',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='vAutor',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='vEditora',
            new_name='Editora',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='vTitulo',
            new_name='Titulo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='vCpf',
            new_name='Cpf',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='vEmail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='dNascimento',
            new_name='Nascimento',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='vNome',
            new_name='Nome',
        ),
    ]
